apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: kube-hello
build:
  tagPolicy:
    customTemplate:
      template: "{{.DATE}}-{{.SHORT_SHA}}"
      components:
      - name: DATE
        dateTime:
          format: "2006-01-02"
          timezone: "UTC"
      - name: SHORT_SHA
        gitCommit:
          variant: AbbrevCommitSha
  artifacts:
  - image: josebiro/kube-hello
deploy:
  kustomize:
    paths:
    - overlays/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - overlays/prod
- name: staging
  deploy:
    kustomize:
      paths:
      - overlays/staging
