apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
nameSuffix: -staging
namespace: staging
images:
- name: josebiro/hello-world
  newTag: v1.0.1-rc1
patchesStrategicMerge:
- stage.yaml
    