apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
nameSuffix: -prod
namespace: production
images:
- name: josebiro/hello-world
  newTag: v1.0.0
patchesStrategicMerge:
- stage.yaml
    